POST http://localhost:8080/tweets
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJteWJhY2tlbmQiLCJzdWIiOiI2MTc2OTcyZi0wNmMxLTRkZDEtODU2Ni0xMmM4MGY5NjNiYTkiLCJleHAiOjE3MjEzMTE3NjMsImlhdCI6MTcyMTMwODc2Mywic2NvcGUiOiJCQVNJQyJ9.eNCHOV4PUaTv5BIqnDsDRmnADqQXUfbWSUtSU90aRHSxGbB7RKEctByj9e73cYDBMiSYtqqMLs3sL2n6GaOSLesXmf-13CFnt9TkUwEDfxfj_H7SDpISKozKQ_arpxkFsfxAI3rtewJVXVLqHZgS361W9_n8rMPIT_H2gLQUwz6sTPwuE0uKd8FtAVm6hPNHFjzDYij1xcokk28lsd48px9xscu9JqMYUNjgnhay4-SNr8NSYC44vBHnE5mHB00T6_UddKwB8vttnJSv22v4CHl6kopvw2QCdCARg7Qdzr0RFGmqKiM-uG-tJm06gbZW6Tn09xCkbvugmgLPo-BMew

{
  "content": "Oi eu sou a lidia"
}

###
DELETE http://localhost:8080/tweets/1
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJteWJhY2tlbmQiLCJzdWIiOiI2MTc2OTcyZi0wNmMxLTRkZDEtODU2Ni0xMmM4MGY5NjNiYTkiLCJleHAiOjE3MjEzMTE3NjMsImlhdCI6MTcyMTMwODc2Mywic2NvcGUiOiJCQVNJQyJ9.eNCHOV4PUaTv5BIqnDsDRmnADqQXUfbWSUtSU90aRHSxGbB7RKEctByj9e73cYDBMiSYtqqMLs3sL2n6GaOSLesXmf-13CFnt9TkUwEDfxfj_H7SDpISKozKQ_arpxkFsfxAI3rtewJVXVLqHZgS361W9_n8rMPIT_H2gLQUwz6sTPwuE0uKd8FtAVm6hPNHFjzDYij1xcokk28lsd48px9xscu9JqMYUNjgnhay4-SNr8NSYC44vBHnE5mHB00T6_UddKwB8vttnJSv22v4CHl6kopvw2QCdCARg7Qdzr0RFGmqKiM-uG-tJm06gbZW6Tn09xCkbvugmgLPo-BMew

###
GET http://localhost:8080/feed
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJteWJhY2tlbmQiLCJzdWIiOiI2MTc2OTcyZi0wNmMxLTRkZDEtODU2Ni0xMmM4MGY5NjNiYTkiLCJleHAiOjE3MjEzMTE3NjMsImlhdCI6MTcyMTMwODc2Mywic2NvcGUiOiJCQVNJQyJ9.eNCHOV4PUaTv5BIqnDsDRmnADqQXUfbWSUtSU90aRHSxGbB7RKEctByj9e73cYDBMiSYtqqMLs3sL2n6GaOSLesXmf-13CFnt9TkUwEDfxfj_H7SDpISKozKQ_arpxkFsfxAI3rtewJVXVLqHZgS361W9_n8rMPIT_H2gLQUwz6sTPwuE0uKd8FtAVm6hPNHFjzDYij1xcokk28lsd48px9xscu9JqMYUNjgnhay4-SNr8NSYC44vBHnE5mHB00T6_UddKwB8vttnJSv22v4CHl6kopvw2QCdCARg7Qdzr0RFGmqKiM-uG-tJm06gbZW6Tn09xCkbvugmgLPo-BMew

